name: spatial_bndry_aug_lag

margin: 1
lambd_min: 1e-6
lambd_max: 1e6
lambd_step: 1
penalty: phr
rho: 1
rho_step: 10
gamma: 1.2
tao: 0.9
vis_lambd_hist: False
normalize: False
is_undersample: False

object:
  _target_: calibrate.lagrangian.SpatialBndAugLagrangian
  num_classes: ${model.num_classes}
  margin: ${lag.margin}
  penalty: ${lag.penalty}
  lambd_min: ${lag.lambd_min}
  lambd_max: ${lag.lambd_max}
  lambd_step: ${lag.lambd_step}
  rho_min: ${lag.rho}
  rho_step: ${lag.rho_step}
  gamma: ${lag.gamma}
  tao: ${lag.tao}
  normalize: ${lag.normalize}
